### ISSUE TITLE
Update to 1.2 Kotlin

### ISSUE THREAD

**Issue by satb** [Xantier/fullstack-kotlin#3]
I keep seeing errors when compiling with Kotlin 1.2. 

Example, take Section 2, Video 3.

In Config.kt

`
 beans{
            bean { ViewRoutes(it.ref())}
        }(ctx)
`

This will give us an error:

`
Expression 'beans{
            bean { ViewRoutes(it.ref())}
        }' of type 'BeanDefinitionDsl' cannot be invoked as a function. The function 'invoke()' is not found
`

Next,  if we change the above method to use the "initialize" method instead of invoke to fix the compilation error like so:

`
 beans{
            bean { ViewRoutes(it.ref())}
        }.initialize(ctx)
`

We get a different compilation error

`
Unresolved reference: it
`

Its very hard to know what the fix is especially when we are going up a learning curve. 

Thank you for your course and hope to know what the fixes are.

**Comment by Xantier** [comment]
Thanks for the comment. 
The issue in this case is Spring unfortunately. They have updated their API and changes the way bean registration with the Kotlin DSL works. 

This is something I can update on the git repository branches.

**Comment by satb** [comment]
Thanks so much. Will wait for the branch update. In the interim, any quick fix for this particular issue that I can incorporate so I can move to the next section of the course?

**Comment by Xantier** [comment]
In newer versions of Spring 5 the `it` keyword is not required any more, `ref()` is available within the same scope as the bean registration block. You should get around the compilation issue by just removing it.

**Comment by satb** [comment]
Thank you. Works!

**Comment by Xantier** [comment]
Kotlin version and Spring dependencies are now updated to 43 branches.
