### ISSUE TITLE
Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain

### ISSUE THREAD

**Issue by karlkras** [Xantier/fullstack-kotlin#5]
Using your Section-1-Video-1 branch to follow your course on packt, clone the repo and any attempts to build/clean/etc. do this:
```✘-127 ~/nikedev/work/fullstack-kotlin [Section-1-Video-1|…4] 
10:02 $ gradlew clean
Picked up _JAVA_OPTIONS: -Djava.net.preferIPv4Stack=true -Duser.timezone=UTC
Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain
✘-1 ~/mydev/work/fullstack-kotlin [Section-1-Video-1|…4] ```

Google hasn't been much help on correcting this, in need of some assistance to get unblocked.

**Comment by Xantier** [comment]
Hi Karlkras, 

The Gradle wrapper JAR file in itself is not included in the repository though the wrapper files are there and wrapper properties are set up. You can run `gradle wrapper` to initialize it and then the command `./gradlew clean/build` etc. would be available for you.

**Comment by karlkras** [comment]
```
User@DESKTOP-PBV4E4I MINGW64 ~/work/fullstack-kotlin (Section-1-Video-1)
$ gradle wrapper
bash: gradle: command not found

User@DESKTOP-PBV4E4I MINGW64 ~/work/fullstack-kotlin (Section-1-Video-1)
$ gradlew wrapper
Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain


```

**Comment by karlkras** [comment]
also:
```
7/14/2018
4:07 PM	Outdated Kotlin Runtime
				Your version of Kotlin runtime in 'Gradle: org.jetbrains.kotlin:kotlin-stdlib:1.1.51' library is 1.1.51, while plugin version is 1.2.30-release-IJ2018.1-1.
				Runtime library should be updated to avoid compatibility problems.
```
don't know the kotlin flavor of gradle well enough to figure out where that dependency reference might be fixed.

**Comment by karlkras** [comment]
and this is working fine from the master branch... but not from the sub branches.

**Comment by Xantier** [comment]
It looks like you don't have Gradle installed. If you install that, you should be able to get forward. Another option is to manually add the `gradle-wrapper.jar` to `gradle/wrapper` folder.

**Comment by karlkras** [comment]
I did this and still same problem.

Sent from Yahoo Mail on Android 
 
  On Sun, Jul 15, 2018 at 10:32 PM, Jussi Hallila<notifications@github.com> wrote:   
It looks like you don't have Gradle installed. If you install that, you should be able to get forward. Another option is to manually add the gradle-wrapper.jar to gradle/wrapper folder.

**Comment by karlkras** [comment]
as mentioned, if I check out master and run gradlew tasks from here it works fine. Not sure why not having a local install of gradle would work differently.
